// Types for the demo-mode time series (generated by devtools/sim/generate-demo-data.ts).
// The series is dateless and tz-less: each day is keyed by a relative offset
// (0 = most recent) and each reading by local time-of-day ("08:15"). Real dates
// are assigned at runtime — see demoDates.ts.

export interface DemoChargeEntry {
  vehicleId: string;
  w: number;
  amps: number;
  soc: number;
  solarC: number;
  gridC: number;
}

export interface DemoReading {
  /** Local time-of-day, e.g. "08:15". */
  time: string;
  solarW: number;
  homeW: number;
  gridW: number;
  charge: DemoChargeEntry[];
}

export interface DemoLog {
  time: string;
  vehicleId: string;
  vehicleName: string;
  action: string;
  detail: string;
  amps: number | null;
  checksJson: string;
}

export interface DemoDay {
  /** Days before today; 0 = most recent. */
  offset: number;
  readings: DemoReading[];
  logs: DemoLog[];
}

export interface DemoVehicleMeta {
  id: string;
  name: string;
  capacityKwh: number;
  chargeLimitPercent: number;
  priority: number;
}

export interface DemoSeries {
  bucketMinutes: number;
  vehicles: DemoVehicleMeta[];
  days: DemoDay[];
}
